import { getRedis } from '../redis/connection.js';
import { emitToUser } from '../socket/websocket.js';
import { enqueueDraftSync } from '../workers/draft-sync.worker.js';
import { logger } from '../../shared/logger.js';

let isListening = false;

export function startEventSubscriber() {
  if (isListening) return;

  // We need a dedicated connection for pub/sub
  const subscriber = getRedis().duplicate();
  const channel = 'draftly:events';

  subscriber.subscribe(channel, (err, count) => {
    if (err) {
      logger.error({ err }, 'Failed to subscribe to Redis events channel');
      return;
    }
    logger.info({ channel, count }, 'Subscribed to Redis events channel');
    isListening = true;
  });

  subscriber.on('message', async (chan, message) => {
    if (chan !== channel) return;
    try {
      const parsed = JSON.parse(message);
      const { type, data } = parsed;
      
      if (!type || !data || !data.userId) {
        logger.warn({ message }, 'Received malformed event from AI Engine');
        return;
      }

      logger.debug({ type, userId: data.userId }, 'Received event from AI Engine');
      
      // Push via WebSocket to the targeted user
      emitToUser(data.userId, type, data);

      // When a draft is generated by the AI Engine, sync it to Gmail Drafts
      if (type === 'draft_generated' && data.draftId && data.threadId) {
        await enqueueDraftSync({
          draftId: data.draftId,
          threadId: data.threadId,
          userId: data.userId,
          correlationId: data.correlationId || `draft-sync-${data.draftId}`,
          action: 'create',
        });
        logger.info({ draftId: data.draftId }, 'Enqueued Gmail draft sync from draft_generated event');
      }
      
    } catch (err) {
      logger.error({ err, message }, 'Error processing Redis event');
    }
  });

  subscriber.on('error', (err) => {
    logger.error({ err }, 'Redis subscriber error');
  });
}

